#!/bin/bash
#{% set use_innerdirs = restic_profile.use_innerdirs|default(False)  %}
#{% set multi = use_innerdirs %}
set -e
cd "$(dirname $(readlink -f "$0"))"
. {{restic_profile_name}}-env
{{restic_profile.wrapper_slug}}
set +e
s=$1
shift
exec "$s" "$@"
