namespace: "corpusops"
name: "roles"
version: "1.0.12"
readme: "README.md"
authors: ["kiorky <kiorky@cryptelium.net>"]
dependencies: []
license: [BSD]
tags: []
repository: "https://github.com/corpusops/roles"
