#!/bin/bash
set -e


cd "$(dirname $(readlink -f "$0"))"
. {{duplicity_profile_name}}-env
{{duplicity_profile.duplicity_slug}}

action=$1
shift

{{duplicity_profile.duplicity_cmd}} $action $( [[ -n $DUPLICITY_DRYRUN ]] && echo "--dry-run -v$DUPLICITY_VERBOSITY"; ) {{duplicity_profile.args.strip()}} ${BACKUP_DEST}${@}
